runtime: python27
api_version: 1
threadsafe: no
# App Engine default is 10m.
default_expiration: "12h"

handlers:
# Storage API.
- url: /storage
  script: storage.py
  secure: always

# Error reporting.
- url: /errorReporter
  script: errorReporter.py
  secure: always

# Gallery API.
- url: /gallery-api/submit
  script: gallery_api/submit.py
  secure: always
- url: /gallery-api/view
  script: gallery_api/view.py
  secure: always
- url: /gallery-api/expire
  script: gallery_api/expire.py
  login: admin
  secure: always
- url: /gallery-api/admin
  script: gallery_api/admin.py
  login: admin
  secure: always

# Source files and uncompiled versions.
skip_files:
# App Engine default patterns.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
